### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by strukturart** [strukturart/greg#29]
- [x] ui fullDay event
- [x] highlight calendar week
- [x] autocomplete locations
- [ ] sync data with serviceworker
- [x] move event in 
- [ ] exporter with RRULE
- [ ] autocomplete category
- [ ] local calendar db structur
